version: '3.5'

services:
  protractor-headless-chrome:
      image: "protractor-headless:chrome"
      build:
        context: "."
        dockerfile: dockerfiles/chrome/Dockerfile
  protractor-headless-firefox:
      image: "protractor-headless:firefox"
      build:
        context: "."
        dockerfile: dockerfiles/firefox/Dockerfile
  protractor-headless-all-browsers:
      image: "protractor-headless:all"
      build:
        context: "."
        dockerfile: dockerfiles/all-browsers/Dockerfile
