#!/bin/bash
set -e

# Parse image name for repo name
repoName=${IMAGE_NAME%%:*}
tag=${IMAGE_NAME##*:}
majorTag=${tag%%.*}
minorTag=${tag%.*}

# Tag and push image for each additional tag
for tag in {${minorTag}, ${majorTag}, latest}; do
    docker tag $IMAGE_NAME ${repoName}:${tag}
    docker push ${repoName}:${tag}
done
