#!/bin/bash
set -e

# Parse image name for repo name
repoName=${IMAGE_NAME%%:*}
tag=${IMAGE_NAME##*:}
majorTag=${tag%%.*}
minorTag=${tag%.*}

# Tag and push image for each additional tag
for newTag in {"${minorTag}","${majorTag}","latest"}; do
    docker tag $IMAGE_NAME ${repoName}:${newTag}
    docker push ${repoName}:${newTag}
done
