#!/bin/bash

MAJORTAG=${DOCKER_TAG%%.*}
MINORTAG=${DOCKER_TAG%.*}

docker push ${DOCKER_REPO}:chrome
docker push ${DOCKER_REPO}:firefox

for newTag in {"${MAJORTAG}","${MINORTAG}","${DOCKER_TAG}"};
do

    # CHROME
    echo "run: docker image tag ${DOCKER_REPO}:chrome ${DOCKER_REPO}:${newTag}-chrome"
    docker image tag ${DOCKER_REPO}:chrome ${DOCKER_REPO}:${newTag}-chrome

    echo "run: docker image push ${DOCKER_REPO}:${newTag}-chrome"
    docker image push ${DOCKER_REPO}:${newTag}-chrome

    # CHROME
    echo "run: docker image tag ${DOCKER_REPO}:firefox ${DOCKER_REPO}:${newTag}-firefox"
    docker image tag ${DOCKER_REPO}:firefox ${DOCKER_REPO}:${newTag}-firefox

    echo "run: docker image push ${DOCKER_REPO}:${newTag}-firefox"
    docker image push ${DOCKER_REPO}:${newTag}-firefox
done
