#!/bin/bash

docker container run \
  --privileged --rm \
  --shm-size 2g \
  -e NPM_INSTALL=true \
  -e SELENIUM_BROWSER=chrome \
  -v $(pwd)/protractor-project:/protractor \
  $DOCKER_REPO:chrome \
  protractor ./conf.js

docker container run \
  --privileged --rm \
  --shm-size 2g \
  -e NPM_INSTALL=true \
  -e SELENIUM_BROWSER=firefox \
  -v $(pwd)/protractor-project:/protractor \
  $DOCKER_REPO:firefox \
  protractor ./conf.js
