name: docker-image-test

on: [ push, pull_request ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker images
      run: docker-compose build
    - name: Run the Docker image - chrome
      run: docker container run -t --privileged -e NPM_INSTALL=true --rm --shm-size 2g -v $(pwd)/protractor-project:/protractor protractor-headless:chrome protractor ./conf.js
    - name: Run the Docker image - firefox
      run: docker container run -t --privileged -e NPM_INSTALL=true --rm --shm-size 2g -v $(pwd)/protractor-project:/protractor protractor-headless:firefox protractor ./conf.js
