name: docker-image-test

on: [ push, pull_request ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker image build . --file Dockerfile --tag protractor-headless
    - name: Run the Docker image
      run: docker container run -t --privileged --rm --shm-size 2g -v $(pwd)/protractor-project:/protractor protractor-headless protractor ./conf.js
