name: test-image-chrome

on: [ push, pull_request ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build Docker image
      run: docker-compose build protractor-headless-chrome
    - name: Run the Docker image
      run: docker-compose up protractor-headless-chrome
